apiVersion: "v1"
appVersion: "[[ .AppVersion ]]"
description: "Chart holding silence-operator."
home: "https://github.com/giantswarm/silence-operator"
name: "silence-operator"
version: "[[ .Version ]]"
annotations:
  config.giantswarm.io/version: 1.x.x
